#!/bin/bash
# -*- mode: sh; coding:utf-8 -*-

LUA_CMD=lua5.3
#LUA_CMD=$(dirname $0)/../clanglua
SCRIPT=$(${LUA_CMD} -e 'print( package.searchpath( "lctags.lctags", package.path ) )')



#echo ${PWD} ':' ${LUA_CMD} ${SCRIPT} $@ > $(dirname $0)/dump

${LUA_CMD} ${SCRIPT} $@ || exit 1
